name: Go

on:
  schedule:
    - cron: '20 02 * * 0'
    - cron: '18 03 * * 1'
    - cron: '21 01 * * 2'
    - cron: '22 03 * * 3'
    - cron: '58 00 * * 4'
    - cron: '11 03 * * 5'
    - cron: '02 01 * * 6'


jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
  
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install easyocr pillow numpy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
      - name: run
        run: STD_ID=${{ secrets.STD_ID }} PASSWORD=${{ secrets.PASSWORD }} python3 main.py
